 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/classes", type: :request do
  # Class. As you add validations to Class, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Class.create! valid_attributes
      get classes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      class = Class.create! valid_attributes
      get class_url(class)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_class_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      class = Class.create! valid_attributes
      get edit_class_url(class)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Class" do
        expect {
          post classes_url, params: { class: valid_attributes }
        }.to change(Class, :count).by(1)
      end

      it "redirects to the created class" do
        post classes_url, params: { class: valid_attributes }
        expect(response).to redirect_to(class_url(Class.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Class" do
        expect {
          post classes_url, params: { class: invalid_attributes }
        }.to change(Class, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post classes_url, params: { class: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested class" do
        class = Class.create! valid_attributes
        patch class_url(class), params: { class: new_attributes }
        class.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the class" do
        class = Class.create! valid_attributes
        patch class_url(class), params: { class: new_attributes }
        class.reload
        expect(response).to redirect_to(class_url(class))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        class = Class.create! valid_attributes
        patch class_url(class), params: { class: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested class" do
      class = Class.create! valid_attributes
      expect {
        delete class_url(class)
      }.to change(Class, :count).by(-1)
    end

    it "redirects to the classes list" do
      class = Class.create! valid_attributes
      delete class_url(class)
      expect(response).to redirect_to(classes_url)
    end
  end
end
